### PR TITLE
add logic to get description from RAWG api and the beginning of unit test

### PR DESCRIPTION
**Pull request by micoolio**

### CODE REVIEW

**Review by chris-oh99 — APPROVED** [review]

**Review by ajdixon30 — APPROVED** [review]

**Review by andrewdpetersen — APPROVED** [review]
Adding the API description and unit test outline looks good

**Review by BrittLowell — CHANGES_REQUESTED** [review]
There are a couple of duplicate methods in the ProjectController and ProjectService.

**Review by andrewdpetersen — APPROVED** [review]
Changes look fine, removing duplicate methods

**Review by BrittLowell — APPROVED** [review]

**Review by BrittLowell — APPROVED** [review]
Looks good

**Review by andrewdpetersen — APPROVED** [review]

**Pull request merged**
